name: Build, Test and Deploy Gastby to gh-pages branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm ci
          export PATH_PREFIX='iblis-gatsby-saas-landing-page'
          export SITE_URL='https://vdelacou.github.io/iblis-gatsby-saas-landing-page/'
          npm run build
      - name: Check Lint
        run: npm run lint
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: vincent.delacourt+github@outlook.com
          build_dir: public
